### ISSUE TITLE
No Response From Cyberpanel API

### ISSUE THREAD

**Issue by Vitalsec** [jetchirag/cyberpanel-whmcs#3] opened 2021-01-10 15:39 UTC
Having issues getting server in whmcs to connect to the shared server, module logging is not giving much on clues.

- whmcs server IP is whitelisted on shared server
- - module is installed correctly
-  Module debug only shows the data included in the connection attempt. The response box is empty.

Test connection in server section fails with a generic error (unknown error). There is nothing in any of the logs even with debug on, I do not see it hitting the shared server.

default of port 8090 is used. Not really sure where to look next..

**Comment by jetchirag** [comment] 2021-01-10 17:38
Read common error #3

**Comment by Vitalsec** [comment] 2021-01-10 19:55
Yes, I checked all of those and confirmed they were ok. Is there any way to make the error more verbose?

**Comment by Zer0Down** [comment] 2021-01-12 11:39
I have found the issue with csf firewall blocking the port for communication with my setup. Most of the time it is the firewall blocking these ports cause errors. Just my 2 cents.

**Comment by jetchirag** [comment] 2021-01-12 12:12
Unknown errors are mostly due to connection errors. Also try with https disabled if hostname is IP.

To check it any further, I'll need some access.

**Comment by Vitalsec** [comment] 2021-01-12 12:46
> I have found the issue with csf firewall blocking the port for communication with my setup. Most of the time it is the firewall blocking these ports cause errors. Just my 2 cents.

That would be what I think as well, but I have checked the ports and telnet connection would have failed if connection was blocked. Also checked to make sure was not WAF doing it.



> Unknown errors are mostly due to connection errors. Also try with https disabled if hostname is IP.
> 
> To check it any further, I'll need some access.

Hostname is not IP and has a good SSL. I did try with SSL disabled as well as a test.

**Comment by blue928** [comment] 2021-03-21 20:12
It's possible my issue is a duplicate of this. If so, please mark as such.
https://github.com/jetchirag/cyberpanel-whmcs/issues/4

Looks like I'm having the same problem. Per @Vitalsec everything server-side is setup correctly. I can access the site on all necessary ports, test connection works fine. There is no firewall on my server. API access is indeed enabled. My issue is exactly the same regardless if I use Hostname with working SSL or with http and ip address. Can confirm that problem persists even if SSL is disabled.

@jetchirag you mention that "Unknown errors are usually connection errors." I'm not getting any errors anywhere at all - no WHMCS errors, no web server errors no system errors.. The only log entry of any kind is the "test connection" attempt which works fine.

**Comment by laikait** [comment] 2022-03-01 18:40
Same problem facing. Did everything correctly. Disabled CSF firewall also, API enabled, IP and hostname are correct. Till now showing "An Unknown Error Occurred"

Here is the module log
===================
Array
(
    [whmcsVersion] => 8.4.0-release.1
    [server] => 1
    [serverid] => 0
    [serverip] => SERVER IP (Hidden)
    [serverhostname] => MY HOSTNAME (Hidden)
    [serverusername] => admin
    [serverpassword] => MY PASSWORD (Hidden)
    [serveraccesshash] => 
    [serversecure] => 1
    [serverhttpprefix] => https
    [serverport] => 8090
    [action] => TestConnection
)

**Comment by jetchirag** [comment] 2022-03-01 19:49
@riyadhtayf This log is from request field. Is Response field empty?

Either whmcs couldn't connect to cyberpanel server or cyberpanel returned incorrect or empty response. I just tested this module with demo cyberpanel and it worked fine.

Check the connectivity from whmcs server to cyberpanel. Try telnet or invoking the cyberpanel api manually.

**Comment by laikait** [comment] 2022-03-02 06:14
> @riyadhtayf This log is from request field. Is Response field empty?
> 
> Either whmcs couldn't connect to cyberpanel server or cyberpanel returned incorrect or empty response. I just tested this module with demo cyberpanel and it worked fine.
> 
> Check the connectivity from whmcs server to cyberpanel. Try telnet or invoking the cyberpanel api manually.

Thanks for your reply. Just now I solved the issue. It was in my first server end. I installed CyberPanel in another server where cPanel was installed in my primary server. Port 8090 was enabled in Cyberpanel Firewall, but the cPanel firewall was blocking the outbound port 8090 where WHMCS was installed. :)

**Closed** 2022-03-02 16:33 UTC
